image: alpine:latest

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - resources/public
      - resources/public/js
      - resources/public/css
  only:
    - master
